image:
  file: .gitpod/Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva
    - djblue.portal

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 6003
    onOpen: ignore
    
tasks:
  - name: Polylith Real World nREPL Server
    command: clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"1.0.0"},cider/cider-nrepl {:mvn/version,"0.28.5"}}}' -M:dev:test:default -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
  - name: Open Getting Started
    command: code development/src/dev/getting_started.clj
  - name: Poly Tool
    command: poly
