version: 2.0

jobs:
  check:
    docker:
      - image: circleci/clojure:tools-deps-1.10.3.855
    working_directory: ~/realworld-example
    steps:
      - checkout
      - run:
          name: Get rid of erroneous git config
          command: |
            rm -rf ~/.gitconfig
      - restore_cache:
          keys:
            - realworld-example-{{ checksum "deps.edn" }}-{{ checksum "projects/realworld-backend/deps.edn" }}
            - realworld-example-
      - run:
          name: Create polylith config if it does not exist
          command: mkdir -p ~/.polylith && echo "{}" > ~/.polylith/config.edn
      - run:
          name: Force clojure to resolve dependencies
          command: clojure -A:dev:test -P
      - run:
          name: Check Polylith workspace
          command: clojure -A:poly check
      - save_cache:
          key: realworld-example-{{ checksum "deps.edn" }}-{{ checksum "projects/realworld-backend/deps.edn" }}
          paths:
            - ~/.polylith
            - ~/.m2
            - ~/.gitlibs
            - ~/.clojure
            - ~/realworld-example/.cpcache
      - persist_to_workspace:
          root: .
          paths:
            - .

  info:
    docker:
      - image: circleci/clojure:tools-deps-1.10.3.855
    working_directory: ~/realworld-example
    steps:
      - attach_workspace:
          at: ~/realworld-example
      - restore_cache:
          keys:
            - realworld-example-{{ checksum "deps.edn" }}-{{ checksum "projects/realworld-backend/deps.edn" }}
      - run:
          name: Add global git user email
          command: git config --global user.email "circleci@polyfy.com"
      - run:
          name: Add global git user name
          command: git config --global user.name "CircleCI"
      - run:
          name: Run ws command for Polylith workspace
          command: clojure -A:poly ws
      - run:
          name: Run info command for Polylith workspace
          command: clojure -A:poly info
      - run:
          name: Run deps command for Polylith workspace
          command: clojure -A:poly deps
      - run:
          name: Run libs command for Polylith workspace
          command: clojure -A:poly libs

  test:
    docker:
      - image: circleci/clojure:tools-deps-1.10.3.855
    working_directory: ~/realworld-example
    steps:
      - attach_workspace:
          at: ~/realworld-example
      - restore_cache:
          keys:
            - realworld-example-{{ checksum "deps.edn" }}-{{ checksum "projects/realworld-backend/deps.edn" }}
      - run:
          name: Add global git user email
          command: git config --global user.email "circleci@polyfy.com"
      - run:
          name: Add global git user name
          command: git config --global user.name "CircleCI"
      - run:
          name: Run tests for Polylith workspace
          command: clojure -A:poly test :project

  api-test:
    docker:
      - image: circleci/clojure:tools-deps-1.10.3.855-node
    working_directory: ~/realworld-example
    steps:
      - attach_workspace:
          at: ~/realworld-example
      - restore_cache:
          keys:
            - realworld-example-{{ checksum "deps.edn" }}-{{ checksum "projects/realworld-backend/deps.edn" }}
      - run:
          name: Run realworld backend
          command: clojure -A:ring
          working_directory: projects/realworld-backend
          background: true
      - run:
          name: Wait for backend to initialize
          command: wget --retry-connrefused --waitretry=10 --read-timeout=20 --timeout=15 -t 30 http://localhost:6003/api/health
      - run:
          name: Run api tests
          command: APIURL=http://localhost:6003/api ./run-api-tests.sh
          working_directory: ~/realworld-example/api-tests

  build-uberjar:
    docker:
      - image: circleci/clojure:tools-deps-1.10.3.855
    working_directory: ~/realworld-example
    steps:
      - attach_workspace:
          at: ~/realworld-example
      - restore_cache:
          keys:
            - realworld-example-{{ checksum "deps.edn" }}-{{ checksum "projects/realworld-backend/deps.edn" }}
      - run:
          name: Build realworld-backed project
          command: ./build-uberjar.sh realworld-backend
      - run:
          name: Copy artifact to artifacts folder
          command: |
            mkdir -p artifacts

            cp projects/realworld-backend/target/realworld-backend.jar artifacts/.
      - store_artifacts:
          path: ./artifacts

  mark-as-stable:
    docker:
      - image: circleci/clojure:tools-deps-1.10.3.855
    working_directory: ~/realworld-example
    steps:
      - attach_workspace:
          at: ~/realworld-example
      - add_ssh_keys:
          fingerprints:
            - "3d:7a:60:40:26:8e:a8:4e:9c:22:fe:77:3f:84:fb:ec"
      - restore_cache:
          keys:
            - realworld-example-{{ checksum "deps.edn" }}-{{ checksum "projects/realworld-backend/deps.edn" }}
      - run:
          name: Add github.com to known hosts
          command: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Add global git user email
          command: git config --global user.email "circleci@polyfy.com"
      - run:
          name: Add global git user name
          command: git config --global user.name "CircleCI"
      - run:
          name: Add git tag to mark this stable point
          command: git tag -f -a "stable-$CIRCLE_BRANCH" -m "[skip ci] Added Stable Polylith tag"
      - run:
          name: Push the new tag
          command: git push origin $CIRCLE_BRANCH --tags --force

workflows:
  version: 2
  validate-test-build:
    jobs:
      - check
      - info:
          requires:
            - check
      - test:
          requires:
            - check
      - api-test:
          requires:
            - test
      - build-uberjar:
          requires:
            - test
      - mark-as-stable:
          requires:
            - api-test
            - build-uberjar
          filters:
            branches:
              only:
                - master
