name: Clojure CI


on:
  push:
    branches: ['master']
#  pull_request:
#    branches: ['main']

jobs:
  check:
    name: Build, poly check, test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.6
        with:
          cli: latest
      - name: Cache deps
        uses: actions/cache@v2
        id: restore-cache
        with:
          path: |
            ~/.polylith
            ~/.m2
            ~/.gitlibs
            ~/.clojure
            ~/bean-counter/.cpcache
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - name: Create polylith config if it does not exist
        run: mkdir -p ~/.polylith && echo "{}" > ~/.polylith/config.edn
      - name: Check Polylith workspace
        run: clojure -M:poly check
      - name: Run Poly info
        run: clojure -M:poly info
      - name: Run tests for polylith workspace
        if: success()
        run: clojure -M:poly test :project
      - name: Run linter
        uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint . --config .clj-kondo/config.edn
          check-name: Linter report
          github_token: ${{ secrets.GITHUB_TOKEN }}