name: CI

on:
  push:
    branches: ['master']

jobs:
  check:
    name: Build, test, poly check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.6
        with:
          cli: latest
      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.polylith
            ~/.m2
            ~/.gitlibs
            ~/.clojure
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - name: Check Polylith workspace
        run: clojure -A:poly check
      - name: Run tests for polylith workspace
        if: success()
        run: clojure -A:poly test :project